{
    "swagger": "2.0",
    "info": {
        "title": "Fitbit Web API Explorer",
        "description": "Fitbit provides a Web API for accessing data from Fitbit activity trackers, Aria scale, and manually entered logs. Anyone can develop an application to access and modify a Fitbit user's data on their behalf, so long as it complies with Fitbit Platform Terms of Service. These Swagger UI docs do not currently support making Fitbit API requests directly. In order to make a request, construct a request for the appropriate endpoint using this documentation, and then add an Aut[...]",
        "version": "1",
        "termsOfService": "https://dev.fitbit.com/legal/platform-terms-of-service/",
        "contact": {
            "name": "Web API Support",
            "url": "https://dev.fitbit.com/build/reference/web-api/help/"
        }
    },
    "host": "api.fitbit.com",
    "tags": [
        {
            "name": "Active Zone Minutes Intraday Time Series",
            "description": "The Active Zone Minutes (AZM) Intraday Time Series endpoints retrieve the user's heart-pumping activity for a specific date or 24 hour period. Intraday support can extend the detail-level response to include 1min, 5min and 15min for Active Zone Minutes."
        },
        {
            "name": "Active Zone Minutes Time Series",
            "description": "The Active Zone Minutes (AZM) Time Series endpoints are used for querying the user's heart-pumping activity throughout the day. "
        },
        {
            "name": "Activity",
            "description": "The Activity endpoints are used to query and/or modify a Fitbit user's daily activity data. "
        },
        {
            "name": "Activity Intraday Time Series",
            "description": "The Activity Intraday Time Series endpoints retrieve the data for a given resource on a specific date or 24 hour period.  Intraday support can extend the detail-level response to include 1min, 5min and 15min for the activity."
        },
        {
            "name": "Activity Time Series",
            "description": "The Activity Time Series endpoints are used to query a Fitbit user's activity data over a period of time, either by specifying a date and time period, or a date range."
        },
        {
            "name": "Authorization",
            "description": "The Authorization endpoints allow an application to onboard Fitbit users who want to share their data with the specified application. The application can initiate the consent flow for new users, obtain the access token and refresh tokens, validate the tokens, and revoke consent to the user."
        },
        {
            "name": "Body",
            "description": "The Body endpoints are used for querying and modifying the user's body fat and weight data."
        },
        {
            "name": "Body Time Series",
            "description": "The Body Time Series endpoints are used for querying body fat and weight data over a period of time either by specifying a date and time period, or a date range."
        },
        {
            "name": "Breathing Rate",
            "description": "Breathing Rate or Respiratory Rate is a measurement of your average breaths per minute at night."
        },
        {
            "name": "Breathing Rate Intraday",
            "description": "The Breathing Rate Intraday endpoint returns the  average breathing rate throughout the day and categories your breathing rate by sleep stage."
        },
        {
            "name": "Cardio Fitness Score (VO2 Max)",
            "description": "The Cardio Fitness Score (also known as VO2 Max) endpoints are used for querying the maximum or optimum rate at which the user’s heart, lungs, and muscles can effectively use oxygen during exercise."
        },
       {
            "name": "Devices",
            "description": "The Devices endpoints displays information about the devices paired to a user's account."
        },
        {
            "name": "Electrocardiogram",
            "description": "The Electrocardiogram (also known as ECG) endpoint is used for querying the user's on-device ECG readings."
        },
        {
            "name": "Friends",
            "description": "The Friends endpoints display information about the specified user's friends and the friend's leaderboard."
        },
        {
            "name": "Heart Rate Intraday Time Series",
            "description": "The Heart Rate Intraday Time Series retrieves the heart rate data on a specific date or 24 hour period. Intraday support can extend the detail-level response to include 1sec, 1min, 5min or 15min for Heart Rate."
        },
        {
            "name": "Heart Rate Time Series",
            "description": "The Heart Rate Time Series endpoints are used for querying the user's heart rate data."
        },
        {
            "name": "Heart Rate Variability",
            "description": "The Heart Rate Variability (HRV) endpoints are used for querying the user’s heart rate variability data."
        },
        {
            "name": "Heart Rate Variability Intraday",
            "description": "The Heart Rate Variability Intraday endpoint returns the HRV rate at various times and returns Root Mean Square of Successive Differences (rmssd), Low Frequency (LF), High Frequency (HF), and Coverage data for a given measurement."
        },
        {
          "name": "Irregular Rhythm Notifications",
          "description": "The Irregular Rhythm Notifications (also known as IRN) endpoints are used for querying the user's engagement with the IRN feature and the alerts received. The IRN API is for research use or investigational use only, and is not intended for clinical or diagnostic purposes."
        },
        {
            "name": "Nutrition",
            "description": "The Nutrition endpoints are used for querying and modifying the food and water data."
        },
        {
            "name": "Nutrition Time Series",
            "description": "The Nutrition Time Series endpoints are used for querying food- and water-related data over a period of time either by specifying a date and time period, or a date range."
        },
        {
            "name": "Sleep",
            "description": "The Sleep endpoints are used for querying and modifying the user’s general sleep data."
        },
        {
            "name": "SpO2",
            "description": "SpO2 (Oxygen Saturation) is a measurement of your blood oxygen level. "
        },
        {
            "name": "SpO2 Intraday",
            "description": "The SpO2 Intraday endpoints return the SpO2 values calculated on a 5-minute exponentially-moving average."
        },
        {
            "name": "Subscriptions",
            "description": "The Subscription endpoints allow an application to request notifications to user's specific data collection."
        },
        {
            "name": "Temperature",
            "description": "The Temperature endpoints are used for querying either the core temperature data logged manually by the user, or the skin temperature recorded by the device while the user is asleep."
        },
        {
            "name": "User",
            "description": "The User endpoints display information about the user's profile information, the regional locale & language settings, and their badges collected"
        }
    ],
    "schemes": [
        "https"
    ],
    "paths": {
        "/oauth2/token": {
            "post": {
                "tags": [
                    "Authorization"
                ],
                "summary": "Get OAuth 2 access token",
                "description": "Retrieves an OAuth 2 access token.",
                "operationId": "oauthToken"
            }
        },
        "/1.1/oauth2/introspect": {
            "post": {
                "tags": [
                    "Authorization"
                ],
                "summary": "Retrieve the active state of an OAuth 2.0 token",
                "description": "Retrieves the active state of an OAuth 2.0 token. It follows https://tools.ietf.org/html/rfc7662.",
                "operationId": "introspect",
                "security": [
                    {
                        "oauth2": []
                    }
                ]
            }
        },
        "/oauth2/revoke": {
            "post": {
                "tags": [
                    "Authorization"
                ],
                "summary": "Revokes consent of the access token or refresh token",
                "description": "Revokes consent of the access token or refresh token",
                "operationId": "revoke",
                "security": [
                    {
                        "oauth2": []
                    }
                ]
            }
        },
        "/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}.json": {
            "get": {
                "tags": [
                    "Active Zone Minutes Intraday Time Series"
                ],
                "summary": "Get AZM Intraday by Date",
                "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.",
                "operationId": "getAZMByDateIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/active-zone-minutes/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json": {
            "get": {
                "tags": [
                    "Active Zone Minutes Intraday Time Series"
                ],
                "summary": "Get AZM Intraday by Date",
                "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date and/or time range.",
                "operationId": "getAZMByDateTimeSeriesIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/{detail-level}.json": {
            "get": {
                "tags": [
                    "Active Zone Minutes Intraday Time Series"
                ],
                "summary": "Get AZM Intraday by Interval",
                "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.",
                "operationId": "getAZMByIntervalIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}/time/{start-time}/{end-time}.json": {
            "get": {
                "tags": [
                    "Active Zone Minutes Intraday Time Series"
                ],
                "summary": "Get AZM Intraday by Interval",
                "description": "Returns the active zone minutes intraday data for a 24 hour period by specifying a date range and/or time range.",
                "operationId": "getAZMByIntervalTimeSeriesIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/active-zone-minutes/date/{date}/{period}.json": {
            "get": {
                "tags": [
                    "Active Zone Minutes Time Series"
                ],
                "summary": "Get AZM Time Series by Date",
                "description": "Returns the daily summary values over a period of time by specifying a date and time period.",
                "operationId": "getAZMTimeSeriesByDate",
                "security": [
                    {
                        "oauth2": [
                            "activity"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/active-zone-minutes/date/{start-date}/{end-date}.json": {
            "get": {
                "tags": [
                    "Active Zone Minutes Time Series"
                ],
                "summary": "Get AZM Time Series by Interval",
                "description": "Returns the daily summary values over an interval by specifying a date range.",
                "operationId": "getAZMTimeSeriesByInterval",
                "security": [
                    {
                        "oauth2": [
                            "activity"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/date/{date}.json": {
            "get": {
                "tags": [
                    "Activity"
                ],
                "summary": "Get Activity Summary by Date ",
                "description": "Retrieves a summary and list of a user's activities and activity log entries for a given day.",
                "operationId": "getActivitiesByDate",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/{resource-path}/date/{base-date}/{end-date}.json": {
            "get": {
                "tags": [
                    "Activity Time Series"
                ],
                "summary": "Get Activity Resource by Date Range",
                "description": "Returns activities time series data in the specified range for a given resource.",
                "operationId": "getActivitiesResourceByDateRange",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/tracker/{resource-path}/date/{base-date}/{end-date}.json": {
            "get": {
                "tags": [
                    "Activity Time Series"
                ],
                "summary": "Get Activity Tracker Resource by Date Range Time Series",
                "description": "Returns time series data in the specified range for a given resource.",
                "operationId": "getActivitiesTrackerResourceByDateRange",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
{ “swagger”： “2.0”， “info”： { “title”： “Fitbit Web API Explorer”， “description”： “Fitbit 提供了一个用于访问 Fitbit 活动追踪器、Aria Scale 和手动录入日志数据的 Web API。”任何人都可以开发应用程序，代表用户访问和修改 Fitbit 用户的数据，只要符合 Fitbit 平台服务条款。这些 Swagger UI 文档目前不支持直接发送 Fitbit API 请求。为了发起请求，请根据此文档构建对相应端点的请求，然后为每个请求添加一个授权头，访问令牌通过以下步骤获得：https://dev.fitbit.com/build/reference/web-api/developer-guide/authorization/.“， ”version“： ”1“， ”conditionsOfService“： ”https://dev.fitbit.com/legal/platform-terms-of-service/“， ”contact“： { ”name“： ”Web API S[...]

        "/1/user/-/activities/{resource-path}/date/{date}/{period}.json": {
            "get": {
                "tags": [
                    "Activity Time Series"
                ],
                "summary": "Get Activity Time Series",
                "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
                "operationId": "getActivitiesResourceByDatePeriod",
“/1/user/-/activities/{resource-path}/date/{date}/{period}.json”： { “get”： { “标签”： [ “活动时间序列” ]， “summary”： “获取活动时间序列”， “description”： “返回指定范围内的指定资源时间序列数据，格式为单位系统中对应提供的 Accept-Language 头。”， “operationId”： “getActivitiesResourceByDatePeriod”， “produces”： [ “application/x-www-form-urlencoded” ]，

                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“参数”： [ { “name”： “resource-path”， “in”： “path”， “description”： “资源路径;详见完整文档中资源路径选项部分的选项。“， ”required“： true， ”type“： ”string“， ”enum“： [ ”calories“， ”caloriesBMR“， ”steps“， ”distance“， ”floors“， ”elevation“， ”minutesSedentary“， ”minutesLightLightActive“， ”minutesFairlyActive“， ”minutesVeryActive“， ”activityCalories“ ]， ”default“： ”steps“ }， { ”name“： ”date“， ”in“： ”path“， ”description“：”格式 yyyy-MM-dd 或今天指定期间的结束日期。“， ”required“： true， ”type“： ”string“， ”format“： “date” }， { “name”： “period”， “in[...]

        "/1/user/-/activities/tracker/{resource-path}/date/{date}/{period}.json": {
            "get": {
                "tags": [
                    "Activity Time Series"
                ],
                "summary": "Get Activity Time Series",
                "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
                "operationId": "getActivitiesTrackerResourceByDatePeriod",
“/1/user/-/activities/tracker/{resource-path}/date/{date}/{period}.json”： { “get”： { “标签”： [ “活动时间序列” ]， “summary”： “获取活动时间序列”， “description”： “返回指定范围内的指定资源时间序列数据，格式为单位系统中对应 Accept-Language 头的单位。”， “operationId”： “getActivitiesTrackerResourceByDatePeriod”， “produces”： [ “application/x-www-form-urlencoded” ]，

                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“参数”： [ { “name”： “resource-path”， “in”： “path”， “description”： “资源路径;详见完整文档中资源路径选项部分的选项。“， ”required“： true， ”type“： ”string“， ”enum“： [ ”calories“， ”caloriesBMR“， ”steps“， ”distance“， ”floors“， ”elevation“， ”minutesSedentary“， ”minutesLightLightActive“， ”minutesFairlyActive“， ”minutesVeryActive“， ”activityCalories“ ]， ”default“： ”steps“ }， { ”name“： ”date“， ”in“： ”path“， ”description“：”格式 yyyy-MM-dd 或今天指定期间的结束日期。“， ”required“： true， ”type“： ”string“， ”format“： “date” }， { “name”： “period”， “in[...]

        "/1/user/-/activities/{resource-path}/date/{base-date}/{end-date}/{detail-level}.json": {
            "get": {
                "tags": [
                    "Activity Intraday Time Series"
                ],
                "summary": "Get Activity Intraday Time Series",
                "description": "Returns the Activity Intraday Time Series for a given resource in the format requested.",
                "operationId": "getActivitiesResourceByDateRangeIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
 “/1/user/-/activities/{resource-path}/date/{base-date}/{end-date}/{detail-level}.json”： { “get”： { “tags”： [ “活动日内时间序列” ]， “summary”： “获取活动日内时间序列”， “description”： “返回指定资源的活动日内时间序列，格式为请求。”， “operationId”： “getActivitiesResourceByDateRangeIntraday”， “produces”： [ “application/x-www-form-urlencoded” ]， “parameters”： [ { “name”： “resource-path”， “in”： “path”， “description”： “the 资源路径;详见完整文档中资源路径选项部分的选项。“， ”required“： true， ”type“： ”string“， ”enum“： [ ”calories“， ”steps“， ”distance“， ”floors“， ”elev[...]

        "/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json": {
            "get": {
                "tags": [
                    "Activity Intraday Time Series"
                ],
                "summary": "Get Intraday Time Series",
                "description": "Returns the Intraday Time Series for a given resource in the format requested.",
                "operationId": "getActivitiesResourceByDateIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}.json”： { “get”： { “tags”： [ “活动日内时间序列” ]， “summary”： “获取日内时间序列”， “description”： “返回指定资源的日间时间序列，格式为请求。”， “operationId”： “getActivitiesResourceByDateIntraday”， “produces”： [ “application/x-www-form-urlencoded” ]， “parameters”： [ { “name”： “resource-path”， “in”： “path”， “description”： “资源路径;详见完整文档中资源路径选项部分的选项。“， ”required“： true， ”type“： ”string“， ”enum“： [ ”calories“， ”steps“， ”distance“， ”floors“， ”elevation“ ]， ”default“： ”steps[...]

        "/1/user/-/activities/{resource-path}/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json": {
            "get": {
                "tags": [
                    "Activity Intraday Time Series"
                ],
                "summary": "Get Activity Intraday Time Series",
                "description": "Returns the Intraday Time Series for a given resource in the format requested.",
                "operationId": "getActivitiesResourceByDateRangeTimeSeriesIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
 “/1/user/-/activities/{resource-path}/date/{end-date}/{detail-level}/time/{start-time}/{end-time}.json”： { “get”： { “tags”： [ “活动日内时间序列” ]， “summary”： “获取活动日内时间序列”， “description”： “返回指定资源的日内时间序列，格式为请求。”， “operationId”： “getActivitiesResourceByDateRangeTimeSeriesIntraday”， “produces”： [ “application/x-www-form-urlencoded” ]， “parameters”： [ { “name”： “resource-path”， “in”： “path”， “描述”：“资源路径;详见完整文档中资源路径选项部分的选项。“， ”required“： true， ”type“： ”string“， ”enum“： [ ”calories“， ”steps“， ”distance“， ”flo[...]

        "/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json": {
            "get": {
                "tags": [
                    "Activity Intraday Time Series"
                ],
                "summary": "Get Intraday Time Series",
                "description": "Returns the Intraday Time Series for a given resource in the format requested.",
                "operationId": "getActivitiesResourceByDateTimeSeriesIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities.json": {
            "post": {
                "tags": [
                    "Activity"
                ],
                "summary": "Log Activity",
                "description": "The Log Activity endpoint creates log entry for an activity or user's private custom activity using units in the unit system which corresponds to the Accept-Language header provided (or using optional custom distanceUnit) and get a response in the format requested.",
                "operationId": "addActivitiesLog",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            },
            "get": {
            "tags": [
                "Activity"
                    ],
            "summary": "Get Lifetime Stats",
            "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
            "operationId": "getActivitiesLog",
                            "security": [
                                {
                                    "oauth2": [
                                        "activity",
                                        "heartrate",
                                        "location",
                                        "nutrition",
                                        "profile",
                                        "settings",
                                        "sleep",
                                        "social",
                                        "weight"
                                    ]
                                }
                            ]
                        }
                    },
 “/1/user/-/activities/{resource-path}/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json”： { “get”： { “tags”： [ “活动日内时间序列” ]， “summary”： “获取日内时间序列”， “description”： “返回指定资源的日间时间序列，格式为请求。”， “operationId”： “getActivitiesResourceByDateTimeSeriesIntraday”， “produces”： [ “application/x-www-form-urlencoded” ]， “parameters”： [ { “name”： “resource-path”， “in”： “path”， “description”： “the 资源路径;详见完整文档中资源路径选项部分的选项。“， ”required“： true， ”type“： ”string“， ”enum“： [ ”calories“， ”steps“， ”distance“[...]

        "/1/user/-/activities/{activity-log-id}.json": {
            "delete": {
                "tags": [
                    "Activity"
                ],
                "summary": "Delete Activity Log",
                "description": "Deletes a user's activity log entry with the given ID.",
                "operationId": "deleteActivitiesLog",
                "security": [
                    {
                        "oauth2": [
                           "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/list.json": {
            "get": {
                "tags": [
                    "Activity"
                ],
                "summary": "Get Activity Log List",
                "description": "Retreives a list of user's activity log entries before or after a given day with offset and limit using units in the unit system which corresponds to the Accept-Language header provided.",
                "operationId": "getActivitiesLogList",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/{log-id}.tcx": {
            "get": {
                "tags": [
                    "Activity"
                ],
                "summary": "Get Activity TCX",
                "description": "Retreives the details of a user's location and heart rate data during a logged exercise activity.",
                "operationId": "getActivitiesTCX",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
         "/1/activities.json": {
            "get": {
                "tags": [
                    "Activity"
                ],
                "summary": "Browse Activity Types",
                "description": "Retreives a tree of all valid Fitbit public activities from the activities catelog as well as private custom activities the user created in the format requested.",
                "operationId": "getActivitiesTypes",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
 “/1/user/-/activities/{activity-log-id}.json”： { “delete”： { “tags”： [ “活动” ]， “summary”： “删除活动日志”， “description”： “删除给定 ID 用户的活动日志条目。”， “operationId”： “deleteActivitiesLog”， “produces”： [ “application/x-www-form-urlencoded” ]， “parameters”： [ { “name”： “activity-log-id”， “in”： “path”， “description”： “活动日志条目的 id.”， “required”： true， “type”： “整数” } ]， “responses”： { “204”： { “description”：“无内容。请求成功了。“ }， ”400“： { ”描述“：”糟糕的请求。请求很可能包含了错误的语法。“ }， ”401“： { ”description“： ”未授权。请求需要用户认证。“ }}， “安全性”： [[...]

        "/1/activities/{activity-id}.json": {
            "get": {
                "tags": [
                    "Activity"
                ],
                "summary": "Get Activity Type",
                "description": "Returns the detail of a specific activity in the Fitbit activities database in the format requested. If activity has levels, it also returns a list of activity level details.",
                "operationId": "getActivitiesTypeDetail",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“/1/activities/{activity-id}.json”： { “get”： { “tags”： [ “活动” ]， “summary”： “获取活动类型”， “description”： “返回 Fitbit 活动数据库中特定活动的详细信息，格式为所需。”如果活动有级别，它还返回活动级别的详细信息列表。“， ”operationId“： ”getActivitiesTypeDetail“， ”produces“： [ ”application/x-www-form-urlencoded“ ]， ”parameters“： [ { ”name“： ”activity-id“， ”in“： ”path“， ”description“： ”活动 ID.“、”required“： true， ”type“： ”string“ }， ”responses“： { ”200“： { ”description“：”一个成功的请求。“}， ”400“： { ”description“：”请求语法错误或本质上无法满足。“}， ”401“： { ”description“：”the 请求需要[...]

        "/1/user/-/activities/frequent.json": {
            "get": {
                "tags": [
                    "Activity"
                ],
                "summary": "Get Frequent Activities",
                "description": "Retreives a list of a user's frequent activities in the format requested using units in the unit system which corresponds to the Accept-Language header provided.",
                "operationId": "getFrequentActivities",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“/1/user/-/activities/frequent.json”： { “get”： { “tags”： [ “活动” ]， “summary”： “获取频繁活动”， “description”： “检索用户常用活动列表，格式为单位系统中的单位，对应于提供的 Accept-Language 头。”， “operationId”： “getFrequentActivities”， “produces”： [ “application/x-www-form-urlencoded” ]， “responses”： { “200”： { “description”： “A successful request.” }， “400”： { “description”：“请求有坏”语法或本质上无法满足。“ }， ”401“： { ”描述“： ”请求需要用户认证。“ }， ”409“： { ”描述“： ”如果给定用户已经用不同的订阅 ID 订阅了该流，或者该订阅 ID 已被用来识别另一流的订阅，则返回。“ } }， ”安全性“： [ { ”oauth2“： [ ”活动“、”心率“、”位置“、[...]

        "/1/user/-/activities/recent.json": {
            "get": {
                "tags": [
                    "Activity"
                ],
                "summary": "Get Recent Activity Types",
                "description": "Retreives a list of a user's recent activities types logged with some details of the last activity log of that type using units in the unit system which corresponds to the Accept-Language header provided.",
                "operationId": "getRecentActivities",
                "security": [
                    {
                        "oauth2": [
                           "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“/1/user/-/activities/recent.json”： { “get”： { “tags”： [ “活动” ]， “summary”： “获取近期活动类型”， “description”： “检索用户近期活动类型列表，并记录该类型最后一次活动日志的详细信息，单位系统对应提供的 Accept-Language 头。”， “operationId”： “getRecentActivities”， “produces”： [ “application/x-www-form-urlencoded” ]， “responses”： { “200”： { “description”：“成功请求。” }， “400”： { “描述”： “请求语法错误或本质上无法满足。”}， “401”： { “描述”： “请求需要用户认证。”}， “409”： { “描述”：“如果给定用户已通过不同的订阅 ID 订阅了该流，或者该订阅 ID 已被用来识别另一流的订阅，则返回。” } }， “安全性”： [ { “oauth2”： [ “活动”、“心率”、“位置”、“营养”、“个人资料”、“设置”、“[...]

        "/1/user/-/activities/favorite.json": {
            "get": {
                "tags": [
                    "Activity"
                ],
                "summary": "Get Favorite Activities",
                "description": "Returns a list of a user's favorite activities.",
                "operationId": "getFavoriteActivities",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“/1/user/-/activities/favorite.json”： { “get”： { “tags”： [ “活动” ]， “summary”： “获取最爱活动”， “description”： “返回用户最爱活动列表。”， “operationId”： “getFavoriteActivities”， “produces”： [ “application/x-www-form-urlencoded” ]， “responses”： { “200”： { “description”： “成功的请求。”}， “400”： { “description”：“请求语法错误或本质上无法满足。”}， “401”： { “description”：“请求需要用户认证。“ }， ”409“： { ”描述“：”如果给定用户已经用不同的订阅 ID 订阅了该流，或者该订阅 ID 已被用来识别另一个流的订阅，则返回。“ } }， ”安全性“： [ { ”oauth2“： [ ”活动“、”心率“、”位置“、”营养“、”个人资料“、”设置“、”睡眠“、”社交“、”体重“ ] } ] } }，

        "/1/user/-/activities/favorite/{activity-id}.json": {
            "delete": {
                "tags": [
                    "Activity"
                ],
                "summary": "Delete Favorite Activity",
                "description": "Removes the activity with the given ID from a user's list of favorite activities.",
                "operationId": "deleteFavoriteActivities",
“/1/user/-/activities/favorite/{activity-id}.json”： { “delete”： { “tags”： [ “活动” ]， “summary”： “删除收藏活动”， “description”： “从用户的收藏活动列表中移除该 ID 的活动。”， “operationId”： “deleteFavoriteActivities”， “produces”： [ “application/x-www-form-urlencoded” ]， “parameters”： [ { “name”： “activity-id”， “in”： “path”， “description”： “被移除活动的 ID.”， “required”： true， “type”： “string” } ]，

                "security": [
                    {
                        "oauth2": [
                           "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
“回复”： { “204”： { “描述”：“无内容。请求成功了。“ }， ”400“： { ”描述“：”糟糕的请求。请求很可能包含了错误的语法。“ }， ”401“： { ”description“： ”未授权。请求需要用户认证。“ }}， “安全性”： [ { “oauth2”： [ “活动”、“心率”、“位置”、“营养”、“个人资料”、“设置”、“睡眠”、“社交”、“体重” ] } ]

            },
             "post": {
                "tags": [
                    "Activity"
                ],
                "summary": "Add Favorite Activity",
                "description": "Adds the activity with the given ID to user's list of favorite activities.",
                "operationId": "addFavoriteActivities",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
              }
        }
}， “post”： { “标签”： [ “活动” ]， “摘要”： “添加收藏活动”， “description”： “将该活动添加到用户的收藏活动列表。”， “operationId”： “addFavoriteActivities”， “produces”： [ “application/x-www-form-urlencoded” ]， “parameters”： [ { “name”： “activity-id”， “in”： “path”， “description”： “活动的编码 ID.”、“required”： true， “type”： “string” } ]， “responses”： { “200”： { “description”： “成功的请求。”}， “201”： { “description”： “the 请求已完成并创建新资源。“ }， ”400“： { ”描述“： ”请求语法错误或本质上无法满足。“}， ”401“： { ”描述“： ”请求需要用户认证。“}， ”409“： { ”描述“：”如果给定用户已经用不同的订阅 ID 订阅了该流，或者该订阅[...]


        "/1/user/-/activities/goals/{period}.json": {
            "get": {
                "tags": [
                    "Activity"
                ],
                "summary": "Get Activity Goals",
                "description": "Retreives a user's current daily or weekly activity goals using measurement units as defined in the unit system, which corresponds to the Accept-Language header provided.",
                "operationId": "getActivitiesGoals",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            },
“/1/user/-/activities/goals/{period}.json”： { “get”： { “标签”： [ “活动” ]， “摘要”： “获取活动目标”， “描述”： “检索用户当前的每日或每周活动目标，使用单位系统中定义的测量单位，对应提供的 Accept-Language 头。”， “operationId”： “getActivitiesGoals”， “produces”： [ “application/x-www-form-urlencoded” ]， “parameters”： [ { “name”： “period”， “in”： “path”， “description”： “每日或每周。”， “required”： true， “类型”： “字符串” } ]， “responses”： { “200”： { “description”： “成功的请求。” }， “400”： { “description”： “请求语法错误或本质上无法满足。”}， “401”： { “description”：“请求需要用户认证。”}， “409”： { “descr[...]

            "post": {
                "tags": [
                    "Activity"
                ],
                "summary": "Update Activity Goals",
                "description": "Updates a user's daily or weekly activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
                "operationId": "addUpdateActivitiesGoals",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“post”： { “标签”： [ “活动” ]， “摘要”： “更新活动目标”， “description”： “更新用户的每日或每周活动目标，并返回使用单位系统中的单位返回响应，该单元对应于提供的 Accept-Language 头。”， “operationId”： “addUpdateActivitiesGoals”， “produces”： [ “application/x-www-form-urlencoded” ]， “parameters”： [ { “name”： “period”， “in”： “path”， “description”：“每日或每周。”， “required”： true， “type”： “string” }， { “name”： “type”， “in”： “query”， “描述”：“目标类型”，“要求”：真，“类型”：“字符串”}，{ “名称”：“值”，“in”：“查询”，“描述”：“目标值”，“要求”：true，“类型”：“字符串” } ]，“响应”： { “200”： { “description”：“一个成功的请求。”}， “400”[...]

        "/1/user/-/body/log/fat/date/{date}.json": {
            "get": {
                "tags": [
                    "Body"
                ],
                "summary": "Get Body Fat Logs",
                "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
                "operationId": "getBodyFatByDate",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“/1/user/-/body/log/fat/date/{date}.json”： { “get”： { “tags”： [ “Body” ]， “summary”： “获取体脂日志”， “description”： “检索所有用户当天体脂日志条目列表，格式为请求。”， “operationId”： “getBodyFatByDate”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “date”， “in”： “path”， “description”： “格式为 yyyy-MM-dd.”， “required”： true， “type”： “string”， “格式”： “日期” }， “responses”： { “200”： { “description”： “成功请求。” }， “400”： { “description”： “请求语法错误或本质上无法满足。”}， “401”： { “description”： “请求需要用户认证。” } }， “安全性”： [ { “oauth2”： [ “活[...]

        "/1/user/-/body/log/fat/date/{date}/{period}.json": {
            "get": {
                "tags": [
                    "Body"
                ],
                "summary": "Get Body Fat Logs",
                "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
                "operationId": "getBodyFatByDatePeriod",
                "security": [
                    {
                        "oauth2": [
                           "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“/1/user/-/body/log/fat/date/{date}/{period}.json”： { “get”： { “tags”： [ “Body” ]， “summary”： “获取体脂日志”， “description”： “检索当天所有用户体脂日志条目列表，格式为请求的。”， “operationId”： “getBodyFatByDatePeriod”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “date”， “in”： “path”， “description”： “格式为 yyyy-MM-dd.”， “required”： true， “type”： “string”， “format”： “date” }， { “name”： “period”， “in”： “path”， “description”： “数据将返回的范围。”选项有：1d、7d、30d、1w、1m、3m、6m、1y 或 max.“，”required“：true，”type“：”string“} ]，”respo[...]

        "/1/user/-/body/log/fat/date/{base-date}/{end-date}.json": {
            "get": {
                "tags": [
                    "Body"
                ],
                "summary": "Get Body Fat Logs",
                "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
                "operationId": "getBodyFatByDateRange",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
         "/1/user/-/body/log/fat.json": {
            "post": {
                "tags": [
                    "Body"
                ],
                "summary": "Log Body Fat",
                "description": "Creates a log entry for body fat and returns a response in the format requested.",
                "operationId": "addBodyFatLog",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/body/log/fat/{body-fat-log-id}.json": {
            "delete": {
                "tags": [
                    "Body"
                ],
                "summary": "Delete Body Fat Log",
                "description": "Deletes a user's body fat log entry with the given ID.",
                "operationId": "deleteBodyFatLog",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/body/log/{goal-type}/goal.json": {
            "get": {
                "tags": [
                    "Body"
                ],
                "summary": "Get Body Goals",
                "description": "Retreives a user's current body fat percentage or weight goal using units in the unit systems that corresponds to the Accept-Language header providedin the format requested.",
                "operationId": "getBodyGoals",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/body/log/fat/goal.json": {
            "post": {
                "tags": [
                    "Body"
                ],
                "summary": "Update Body Fat Goal",
                "description": "Updates user's fat percentage goal.",
                "operationId": "UpdateBodyFatGoal",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/body/log/weight/goal.json": {
            "post": {
                "tags": [
                    "Body"
                ],
                "summary": "Update Weight Goal",
                "description": "Updates user's fat percentage goal.",
                "operationId": "updateWeightGoal",
                "security": [
                    {
                        "oauth2": [
                            "profile",
                            "heartrate",
                            "location"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/body/log/weight/date/{date}.json": {
            "get": {
                "tags": [
                    "Body"
                ],
                "summary": "Get Weight Logs",
                "description": "Retreives a list of all user's body weight log entries for a given day using units in the unit systems which corresponds to the Accept-Language header provided.",
                "operationId": "getWeightByDate",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/body/log/weight/date/{date}/{period}.json": {
            "get": {
                "tags": [
                    "Body"
                ],
                "summary": "Get Body Fat Logs",
                "description": "Retreives a list of all user's body weight log entries for a given day in the format requested.",
                "operationId": "getWeightByDatePeriod",
                "security": [
                    {
                        "oauth2": [
                           "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
 “/1/user/-/body/log/fat/date/{base-date}/{end-date}.json”： { “get”： { “tags”： [ “Body” ]， “summary”： “获取体脂日志”， “description”： “检索当天所有用户体脂日志条目列表，格式为请求的。”， “operationId”： “getBodyFatByDateRange”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “base-date”， “in”： “path”， “description”： “range 起始日期格式为 yyyy-MM-dd 或今天。”， “required”： true， “type”： “string”， “format”： “date” }， { “name”： “end-date”， “in”： “path”， “description”： “该范围的结束日期。”， “required”： true， “type”： “string”， “format”： “d[...]

        "/1/user/-/body/log/weight/date/{base-date}/{end-date}.json": {
            "get": {
                "tags": [
                    "Body"
                ],
                "summary": "Get Body Fat Logs",
                "description": "Retreives a list of all user's body fat log entries for a given day in the format requested.",
                "operationId": "getWeightByDateRange",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“/1/user/-/body/log/weight/date/{base-date}/{end-date}.json”： { “get”： { “tags”： [ “Body” ]， “summary”： “获取体脂日志”， “description”： “检索当天所有用户体脂日志条目列表，格式为请求的。”， “operationId”： “getWeightByDateRange”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “base-date”， “in”： “path”， “description”： “range 起始日期格式为 yyyy-MM-dd 或今天。”， “required”： true， “type”： “string”， “format”： “date” }， { “name”： “end-date”， “in”： “path”， “description”： “该范围的结束日期。”， “required”： true， “type”： “string”， “format”： “[...]

        "/1/user/-/body/log/weight.json": {
            "post": {
                "tags": [
                    "Body"
                ],
                "summary": "Log Weight",
                "description": "Creates log entry for a body weight using units in the unit systems that corresponds to the Accept-Language header provided and gets a response in the format requested.",
                "operationId": "addWeightLog",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/body/log/weight/{body-weight-log-id}.json": {
            "delete": {
                "tags": [
                    "Body"
                ],
                "summary": "Delete Weight Log",
                "description": "Deletes a user's body weight log entrywith the given ID.",
                "operationId": "deleteWeightLog",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/body/{resource-path}/date/{date}/{period}.json": {
            "get": {
                "tags": [
                    "Body Time Series"
                ],
                "summary": "Get Body Time Series",
                "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
                "operationId": "getBodyResourceByDatePeriod",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/body/{resource-path}/date/{base-date}/{end-date}.json": {
            "get": {
                "tags": [
                    "Body Time Series"
                ],
                "summary": "Get Body Time Series",
                "description": "Returns time series data in the specified range for a given resource in the format requested using units in the unit system that corresponds to the Accept-Language header provided.",
                "operationId": "getBodyResourceByDateRange",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/br/date/{date}.json": {
            "get": {
                "tags": [
                    "Breathing Rate"
                ],
                "summary": "Get Breathing Rate Summary by Date",
                "description": "This endpoint returns average breathing rate data for a single date. Breathing Rate data applies specifically to a user’s “main sleep,” which is the longest single period of time during which they were asleep on a given date.",
                "operationId": "getBreathingRateSummaryByDate",
                "security": [
                    {
                        "oauth2": [
                           "respiratory_rate"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/br/date/{startDate}/{endDate}.json": {
            "get": {
                "tags": [
                    "Breathing Rate"
                ],
                "summary": "Get Breathing Rate Summary by Interval",
                "description": "This endpoint returns average breathing rate data for a date range. Breathing Rate data applies specifically to a user’s “main sleep,” which is the longest single period of time during which they were asleep on a given date.",
                "operationId": "getBreathingRateSummaryByInterval",
                "security": [
                    {
                        "oauth2": [
                           "respiratory_rate"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/br/date/{date}/all.json": {
            "get": {
                "tags": [
                    "Breathing Rate Intraday"
                ],
                "summary": "Get Breathing Rate Intraday by Date",
                "description": "This endpoint returns intraday breathing rate data for a single date. It measures the average breathing rate throughout the day and categories your breathing rate by sleep stage. Sleep stages vary between light sleep, deep sleep, REM sleep, and full sleep.",
                "operationId": "getBreathingRateIntradayByDate",
                "security": [
                    {
                        "oauth2": [
                           "respiratory_rate"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/br/date/{startDate}/{endDate}/all.json": {
            "get": {
                "tags": [
                    "Breathing Rate Intraday"
                ],
                "summary": "Get Breathing Rate Intraday by Interval",
                "description": "This endpoint returns intraday breathing rate data for a date range. It measures the average breathing rate throughout the day and categories your breathing rate by sleep stage. Sleep stages vary between light sleep, deep sleep, REM sleep, and full sleep.",
                "operationId": "getBreathingRateIntradayByInterval",
                "security": [
                    {
                        "oauth2": [
                           "respiratory_rate"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/cardioscore/date/{date}.json": {
            "get": {
                "tags": [
                    "Cardio Fitness Score (VO2 Max)"
                ],
                "summary": "Get VO2 Max Summary by Date",
                "description": "This endpoint returns the Cardio Fitness Score (VO2 Max) data for a single date. VO2 Max values will be shown as a range if no run data is available or a single numeric value if the user uses a GPS for runs.",
                "operationId": "getVo2MaxSummaryByDate",
                "security": [
                    {
                        "oauth2": [
                           "cardio_fitness"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/cardioscore/date/{startDate}/{endDate}.json": {
            "get": {
                "tags": [
                    "Cardio Fitness Score (VO2 Max)"
                ],
                "summary": "Get VO2 Max Summary by Interval",
                "description": "This endpoint returns the Cardio Fitness Score (VO2 Max) data for a date range. VO2 Max values will be shown as a range if no run data is available or a single numeric value if the user uses a GPS for runs.",
                "operationId": "getVo2MaxSummaryByInterval",
                "security": [
                    {
                        "oauth2": [
                           "cardio_fitness"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/devices.json": {
            "get": {
                "tags": [
                    "Devices"
                ],
                "summary": "Get Devices",
                "description": "Returns a list of the Fitbit devices connected to a user's account.",
                "operationId": "getDevices",
                "security": [
                    {
                        "oauth2": [
                           "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/devices/tracker/{tracker-id}/alarms.json": {
            "get": {
                "tags": [
                    "Devices"
                ],
                "summary": "Get Alarms",
                "description": "Returns alarms for a device",
                "operationId": "getAlarms",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
        },
            "post": {
                "tags": [
                    "Devices"
                ],
                "summary": "Add Alarm",
                "description": "Adds the alarm settings to a given ID for a given device.",
                "operationId": "addAlarms",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
 “/1/user/-/body/log/weight.json”： { “post”： { “tags”： [ “Body” ]， “summary”： “Log Weight”， “description”： “使用单位系统中的单位创建对应 Accept-Language 头部的体重日志条目，并获得请求格式的响应。”， “operationId”： “addWeightLog”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “weight”， “in”： “query”， “description”： “权重格式为 X.XX.”， “required”： true， “type”： “integer” }， { “name”： “date”， “in”： “query”， “description”： “log 条目日期格式为 yyyyy-MM-dd.”， “required”： true， “type”： “string”， “format”： “date” }， { “name”： “time”， [...]

        "/1/user/-/devices/tracker/{tracker-id}/alarms/{alarm-id}.json": {
            "post": {
                "tags": [
                    "Devices"
                ],
                "summary": "Update Alarm",
                "description": "Updates the alarm entry with a given ID for a given device. It also gets a response in the format requested.",
                "operationId": "updateAlarms",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Devices"
                ],
                "summary": "Delete Alarm",
                "description": "Deletes the user's device alarm entry with the given ID for a given device.",
                "operationId": "deleteAlarms",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/ecg/list.json": {
            "get": {
                "tags": [
                    "Electrocardiogram"
                ],
                "summary": "Get ECG Log List",
                "description": "This endpoint is used for querying the user's on-device ECG readings.",
                "operationId": "getEcgLogList",
                "security": [
                    {
                        "oauth2": [
                            "electrocardiogram"
                        ]
                    }
                ]
            }
        },
        "/1.1/user/-/friends.json": {
            "get": {
                "tags": [
                    "Friends"
                ],
                "summary": "Get Friends",
                "description": "Returns data of a user's friends in the format requested using units in the unit system which corresponds to the Accept-Language header provided.",
                "operationId": "getFriends",
                "security": [
                    {
                        "oauth2": [
                            "social"
                        ]
                    }
                ]
            }
        },
        "/1.1/user/-/leaderboard/friends.json": {
            "get": {
                "tags": [
                    "Friends"
                ],
                "summary": "Get Friends Leaderboard",
                "description": "Returns data of a user's friends in the format requested using units in the unit system which corresponds to the Accept-Language header provided.",
                "operationId": "getFriendsLeaderboard",
                "security": [
                    {
                        "oauth2": [
                            "social"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/heart/date/{date}/{period}.json": {
            "get": {
                "tags": [
                    "Heart Rate Time Series"
                ],
                "summary": "Get Heart Rate Time Series",
                "description": "Returns the time series data in the specified range for a given resource in the format requested using units in the unit systems that corresponds to the Accept-Language header provided.",
                "operationId": "getHeartByDatePeriod",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/heart/date/{base-date}/{end-date}.json": {
            "get": {
                "tags": [
                    "Heart Rate Time Series"
                ],
                "summary": "Get Heart Rate Time Series",
                "description": "Returns the time series data in the specified range for a given resource in the format requested using units in the unit systems that corresponds to the Accept-Language header provided.",
                "operationId": "getHeartByDateRange",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/heart/date/{date}/{end-date}/{detail-level}.json": {
            "get": {
                "tags": [
                    "Heart Rate Intraday Time Series"
                ],
                "summary": "Get Heart Rate Intraday Time Series",
                "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the auth[...]",
                "operationId": "getHeartByDateRangeIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/activities/heart/date/{date}/{end-date}/{detail-level}/time/{start-time}/{end-time}.json": {
            "get": {
                "tags": [
                    "Heart Rate Intraday Time Series"
                ],
                "summary": "Get Heart Rate Intraday Time Series",
                "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the auth[...]",
                "operationId": "getHeartByDateRangeTimestampIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
 “/1/user/-/devices/tracker/{tracker-id}/alarms/{alarm-id}.json”： { “post”： { “tags”： [ “Devices” ]， “summary”： “更新警报”， “description”： “更新某个设备的指定 ID 的警报条目。它还会收到以下格式的响应。“， ”operationId“： ”updateAlarms“， ”produces“： [ ”application/json“ ]， ”parameters“： [ { ”name“： ”tracker-id“， ”in“： ”path“， ”description“：”返回数据的追踪器的 ID。tracker-id 值通过获取设备端点“， ”required“： true， ”type“： ”整数“ }， { ”name“： ”alarm-id“， ”in“： ”path“， ”description“： ”待更新警报的 ID“，alarm-id 值可在获取活动端点的响应中找到。“， ”required“： true， ”type“： ”integ[...]

        "/1/user/-/activities/heart/date/{date}/1d/{detail-level}.json": {
            "get": {
                "tags": [
                    "Heart Rate Intraday Time Series"
                ],
                "summary": "Get Heart Rate Intraday Time Series",
                "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the auth[...]",
                "operationId": "getHeartByDateIntraday",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
“/1/user/-/activities/heart/date/{date}/1d/{detail-level}.json”： { “get”： { “标签”： [ “日内心率时间序列” ]， “摘要”： “获取日内时间序列心率”， “description”： “返回指定资源的日内时间序列，格式为所需。如果您的应用拥有相应访问权限，您对特定日期的时间序列端点进行调用（通过使用同一天的开始和结束日期或 1 天的时间段），响应将包含延长的日内值，并对应当天的详细程度为一分钟。与其他允许获取其他用户数据的时间序列调用不同，日内数据仅供授权用户使用。“， ”operationId“： ”getHeartByDateIntraday“， ”produces“： [ ”application/json“ ]， ”parameters“： [ { ”name“： ”date“， ”in“： ”path“， ”description“： ”yyyy-MM-dd 格式的日期或今天。“， ”required“： true， ”type“： ”string“， ”format“： ”date“ }， {[...]

        "/1/user/-/activities/heart/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json": {
            "get": {
                "tags": [
                    "Heart Rate Intraday Time Series"
                ],
                "summary": "Get Heart Rate Intraday Time Series",
                "description": "Returns the intraday time series for a given resource in the format requested. If your application has the appropriate access, your calls to a time series endpoint for a specific day (by using start and end dates on the same day or a period of 1d), the response will include extended intraday values with a one-minute detail level for that day. Unlike other time series calls that allow fetching data of other users, intraday data is available only for and to the auth[...]",
                "operationId": "getHeartByDateTimestampIntraday",
                "security": [
                    {
                        "oauth2": [
                           "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/hrv/date/{date}.json": {
            "get": {
                "tags": [
                    "Heart Rate Variability"
                ],
                "summary": "Get HRV Summary by Date",
                "description": "This endpoint returns the Heart Rate Variability (HRV) data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
                "operationId": "getHrvSummaryDate",
                "security": [
                    {
                        "oauth2": [
                           "heartrate"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/hrv/date/{startDate}/{endDate}.json": {
            "get": {
                "tags": [
                    "Heart Rate Variability"
                ],
                "summary": "Get HRV Summary by Interval",
                "description": "This endpoint returns the Heart Rate Variability (HRV) data for a date range. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
                "operationId": "getHrvSummaryInterval",
                "security": [
                    {
                        "oauth2": [
                           "heartrate"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/hrv/date/{date}/all.json": {
            "get": {
                "tags": [
                    "Heart Rate Variability Intraday"
                ],
                "summary": "Get HRV Intraday by Date",
                "description": "This endpoint returns the Heart Rate Variability (HRV) intraday data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
                "operationId": "getHrvIntradayByDate",
                "security": [
                    {
                        "oauth2": [
                           "heartrate"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/hrv/date/{startDate}/{endDate}/all.json": {
            "get": {
                "tags": [
                    "Heart Rate Variability Intraday"
                ],
                "summary": "Get HRV Intraday by Interval",
                "description": "This endpoint returns the Heart Rate Variability (HRV) intraday data for a single date. HRV data applies specifically to a user’s “main sleep,” which is the longest single period of time asleep on a given date.",
                "operationId": "getHrvIntradayByInterval",
                "security": [
                    {
                        "oauth2": [
                           "heartrate"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/irn/alerts/list.json": {
            "get": {
                "tags": [
                    "Irregular Rhythm Notifications"
                ],
                "summary": "Get IRN Alerts List",
                "description": "This endpoint returns a paginated list of Irregular Rhythm Notifications (IRN) alerts, as well as all of the alert tachograms. This endpoint will only return alerts that the user has read in the Fitbit app already, as that is meant as the primary entrypoint for viewing notifications.",
                "operationId": "getIrnAlertsList",
                "security": [
                    {
                        "oauth2": [
                            "irregular_rhythm_notifications"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/irn/profile.json": {
            "get": {
                "tags": [
                    "Irregular Rhythm Notifications"
                ],
                "summary": "Get IRN Profile",
                "description": "This endpoint returns the user state for Irregular Rhythm Notifications (IRN). The user state contains most information about the user’s current engagement with the feature, including onboarding progress and algorithm processing state.",
                "operationId": "getIrnProfile",
                "security": [
                    {
                        "oauth2": [
                            "irregular_rhythm_notifications"
                        ]
                    }
                ]
            }
        },
        "/1/foods/locales.json": {
            "get": {
                "tags": [
                    "Nutrition"
                ],
                "summary": "Get Food Locales",
                "description": "Returns the food locales that the user may choose to search, log, and create food in.",
                "operationId": "getFoodsLocales",
                "security": [
                    {
                        "oauth2": [
                            "nutrition"
                        ]
                    }
                ]
            }
          },
          "/1/user/-/foods/log/goal.json": {
              "get": {
                  "tags": [
                    "Nutrition"
                  ],
                  "summary": "Get Food Goals",
                  "description": "Returns a user's current daily calorie consumption goal and/or foodPlan value in the format requested.",
                  "operationId": "getFoodsGoal",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              },
 “/1/user/-/activities/heart/date/{date}/1d/{detail-level}/time/{start-time}/{end-time}.json”： { “get”： { “标签”： [ “心率日内时间序列” ]， “摘要”： “获取心率日内时间序列”， “description”：“返回指定资源的日内时间序列，格式为所需。如果您的应用拥有相应访问权限，您对特定日期的时间序列端点进行调用（通过使用同一天的开始和结束日期或 1 天的时间段），响应将包含延长的日内值，并对应当天的详细程度为一分钟。与其他允许获取其他用户数据的时间序列调用不同，日内数据仅对授权用户开放。“， ”operationId“： ”getHeartByDateTimestampIntraday“， ”produces“： [ ”application/json“ ]， ”parameters“： [ { ”name“： ”date“， ”in“： ”path“， ”description“： ”yyyy-MM-dd 格式的日期或今天。“， ”required“： true， ”[...]

              "post": {
                  "tags": [
                    "Nutrition"
                  ],
                  "summary": "Update Food Goal",
                  "description": "Updates a user's daily calories consumption goal or food plan and returns a response in the format requested.",
                  "operationId": "addUpdateFoodsGoal",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“post”： { “标签”： [ “营养” ]， “摘要”： “更新食物目标”， “描述”： “更新用户每日热量摄入目标或饮食计划，并返回要求格式的回复。”， “operationId”： “addUpdateFoodsGoal”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “calories”， “in”： “query”， “description”： “必须手动提供热量或强度的卡路里摄入目标。”， “required”： true， “type”： “整数” }， { “name”： “intensity”， “in”： “查询”、“描述”：“饮食计划强度（维持、简单、中等、有点困难或困难）。必须提供热量或强度。“， ”required“： false， ”type“： ”string“ }， { ”name“： ”personalized“， ”in“： ”query“， ”description“：”饮食计划类型;true.“， ”required“： false， ”type“： ”stri[...]


          "/1/user/-/foods/log/date/{date}.json": {
              "get": {
                  "tags": [
                    "Nutrition"
                  ],
                  "summary": "Get Food Logs",
                  "description": "Retreives a summary and list of a user's food log entries for a given day in the format requested.",
                  "operationId": "getFoodsByDate",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
          "/1/user/-/foods/log/water/date/{date}.json": {
              "get": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Get Water Logs",
                  "description": "Retreives a summary and list of a user's water log entries for a given day in the requested using units in the unit system that corresponds to the Accept-Language header provided.",
                  "operationId": "getWaterByDate",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
 “/1/user/-/foods/log/date/{date}.json”： { “get”： { “tags”： [ “Nutrition” ]， “summary”： “获取食物日志”， “description”： “检索用户当天的食物日志条目摘要和列表，格式为所需。”， “operationId”： “getFoodsByDate”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “date”， “in”： “path”， “description”： “需返回记录的日期。”格式为 yyyy-MM-dd.“， ”required“： true， ”type“： ”string“， ”format“： ”date“ }， ”responses“： { ”200“： { ”description“： ”A successful request.“ }， ”400“： { ”description“：”请求语法错误或本质上无法满足。“}， ”401“： { ”description“： ”请求需要用户认[...]

          "/1/user/-/foods/log/water/goal.json": {
              "get": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Get Water Goal",
                  "description": "Retreives a summary and list of a user's water goal entries for a given day in the requested using units in the unit system that corresponds to the Accept-Language header provided.",
                  "operationId": "getWaterGoal",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              },
              "post": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Update Water Goal",
                  "description": "Updates a user's daily calories consumption goal or food plan and returns a response in the format requested.",
                  "operationId": "addUpdateWaterGoal",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“/1/user/-/foods/log/water/goal.json”： { “get”： { “tags”： [ “营养” ]， “summary”： “获取水目标”， “description”： “检索用户在请求的单位系统中，使用单位在特定日内的水资源目标条目摘要和列表，该单位对应于提供的 Accept-Language 头部。”， “operationId”： “getWaterGoal”， “produces”： [ “application/json” ]， “responses”： { “200”： { “description”： “A successful request.” } }， “security”： [ { “oauth2”： [ “营养” ] } }， “post”： { “标签”： [ “营养” ]， “summary”： “更新水目标”， “description”： “更新用户每日热量摄入目标或饮食计划，并返回所需格式的回复。”， “operationId”： “addUpdateWaterGoal”， “produces”： [ “applic[...],

          "/1/user/-/foods/log/{resource-path}/date/{base-date}/{end-date}.json": {
              "get": {
                  "tags": [
                      "Nutrition Time Series"
                  ],
                  "summary": "Get Food or Water Time Series",
                  "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
                  "operationId": "getFoodsByDateRange",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“/1/user/-/foods/log/{resource-path}/date/{base-date}/{end-date}.json”： { “get”： { “tags”： [ “营养时间序列” ]， “summary”： “获取食物或水时间序列”， “description”： “更新用户的每日活动目标，并返回单位系统中的响应，对应于提供的 Accept-Language 头。”， “operationId”： “getFoodsByDateRange”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “resource-path”， “in”： “path”， “description”： “资源之路。详见完整文档中“解决方案路径选项”部分的选项。“， ”required“： true， ”type“： ”string“， ”enum“： [ ”caloriesIn“， ”water“ ]， ”default“： ”caloriesIn“ }， { ”name“： ”base-date“， ”in[...]

          "/1/user/-/foods/log/{resource-path}/date/{date}/{period}.json": {
              "get": {
                  "tags": [
                      "Nutrition Time Series"
                  ],
                  "summary": "Get Food or Water Time Series",
                  "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
                  "operationId": "getFoodsResourceByDatePeriod",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“/1/user/-/foods/log/{resource-path}/date/{date}/{period}.json”： { “get”： { “tags”： [ “营养时间序列” ]， “summary”： “获取食物或水时间序列”， “description”： “更新用户的每日活动目标，并使用单位系统中的单位返回响应，该单位对应于提供的 Accept-Language 头。”， “operationId”： “getFoodsResourceByDatePeriod”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “resource-path”， “in”： “path”， “description”： “资源之路。详见完整文档中“解决方案路径选项”部分的选项。“， ”required“： true， ”type“： ”string“， ”enum“： [ ”caloriesIn“， ”water“ ]， ”default“： ”caloriesIn“ }， { ”name“： ”date“，[...],

          "/1/user/-/foods/log.json": {
              "post": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Log Food",
                  "description": "Creates food log entries for users with or without foodId value.",
                  "operationId": "addFoodsLog",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
           "/1/user/-/foods/log/{food-log-id}.json": {
              "delete": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Delete Food Log",
                  "description": "Deletes a user's food log entry with the given ID.",
                  "operationId": "deleteFoodsLog",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              },
               "post": {
                   "tags": [
                       "Nutrition"
                   ],
                   "summary": "Edit Food Log",
                   "description": "The Edit Food Log endpoint changes the quantity or calories consumed for a user's food log entry with the given Food Log ID.",
                   "operationId": "editFoodsLog",
                   "security": [
                       {
                           "oauth2": [
                            "nutrition"
                           ]
                       }
                   ]
               }
          },
          "/1/user/-/foods/log/water.json": {
              "post": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Log Water",
                  "description": "Creates a log entry for water using units in the unit systems that corresponds to the Accept-Language header provided.",
                  "operationId": "addWaterLog",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
          "/1/user/-/foods/log/water/{water-log-id}.json": {
              "delete": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Delete Water Log",
                  "description": "Deletes a user's water log entry with the given ID.",
                  "operationId": "deleteWaterLog",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
 “/1/user/-/foods/log.json”： { “post”： { “标签”： [ “营养” ]， “summary”： “Log Food”， “description”： “为用户创建有无 foodID 值的食品日志条目。”， “operationId”： “addFoodsLog”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “foodId”， “in”： “query”， “description”： “待记录食物的 ID。”必须提供 foodID 或 foodName 之一。“、”required“： true， ”type“： ”string“ }， { ”name“： ”foodName“， ”in“： ”query“， ”description“： ”Food entry name.必须提供 foodId 或 foodName。“， ”required“： false， ”type“： ”string“ }， { ”name“： ”mealTypeId“， ”in“： ”qu[...]

                  ]
              },
              "post": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Update Water Log",
                  "description": "Updates a user's water log entry with the given ID.",
                  "operationId": "updateWaterLog",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
] }， “post”： { “标签”： [ “营养” ]， “summary”： “更新水日志”， “description”： “更新用户的水日志条目，使用给定的 ID。”， “operationId”： “updateWaterLog”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “water-log-id”， “in”： “path”， “description”： “将删除的 waterUnit 日志条目的 ID.”， “required”： true， “type”： “string” }， { “name”： “amount”， “in”： “query”， “description”： “消耗量;格式为 X.X，且在指定的 waterUnit 中，或对应于 Accept-Language 头部的单位系统中。“， ”required“： true， ”type“： ”string“ }， { ”name“： ”unit“， ”in“： ”query“， ”description“：”水测量单[...]

                  ]
              }
          },
          "/1/user/-/foods/log/favorite.json": {
              "get": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Get Favorite Foods",
                  "description": "Returns a list of a user's favorite foods in the format requested. A favorite food in the list provides a quick way to log the food via the Log Food endpoint.",
                  "operationId": "getFavoriteFoods",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          }
] } }， “/1/user/-/foods/log/favorite.json”： { “get”： { “tags”： [ “Nutrition” ]， “summary”： “获取喜欢的食物”， “description”： “返回用户偏好食物列表，格式符合要求。列表中的收藏食物通过 Log Food 端点快速记录食物。“， ”operationId“： ”getFavoriteFoods“， ”produces“： [ ”application/json“ ]， ”responses“： { ”200“： { ”description“：”Successful request.“ }， ”400“： { ”description“： ”请求语法错误或本质上无法满足。“}， ”401“： { ”description“： ”请求需要用户认证。“ }， ”403“： { ”description“： ”服务器理解了请求， 但却拒绝履行这个承诺。”}， “安全”： [ { “OUth2”： [ “营养” ] } } }，

          "/1/user/-/foods/log/frequent.json": {
              "get": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Get Frequent Foods",
                  "description": "Returns a list of a user's frequent foods in the format requested. A frequent food in the list provides a quick way to log the food via the Log Food endpoint.",
                  "operationId": "getFrequentFoods",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
            },
“/1/user/-/foods/log/frequent.json”： { “get”： { “tags”： [ “营养” ]， “summary”： “获取常见食物”， “description”： “返回用户常用食物列表，格式为所需。列表中的频繁食物可以通过 Log Food 端点快速记录食物。“， ”operationId“： ”getFrequentFoods“， ”produces“： [ ”application/json“ ]， ”responses“： { ”200“： { ”description“： ”成功请求。“ }， ”400“： { ”description“：”请求语法错误或本质上无法满足。“}， ”401“： { ”description“： ”请求需要用户认证。“}， ”403“： { ”description“： ”服务器理解了请求， 但却拒绝履行这个承诺。”}， “安全”： [ { “OUth2”： [ “营养” ] } } }，

          "/1/user/-/foods/log/favorite/{food-id}.json": {
              "post": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Add Favorite Food",
                  "description": "Updates a user's daily activity goals and returns a response using units in the unit system which corresponds to the Accept-Language header provided.",
                  "operationId": "addFavoriteFood",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
“/1/user/-/foods/log/favorite/{food-id}.json”： { “post”： { “tags”： [ “营养” ]， “summary”： “添加最爱食物”， “description”： “更新用户每日活动目标，并返回单位系统中的响应，该单位对应于提供的 Accept-Language 头。”， “operationId”： “addFavoriteFood”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “food-id”， “in”： “path”， “description”： “添加到用户收藏夹的食物 ID”， “required”： true， “type”： “string” } ]， “responses”： { “200”： { “description”： “Successful request.” }， “400”： { “description”： “请求语法错误或本质上无法满足。”}， “401”： { “description”：“请求需要用户[...]

          },


              "delete": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Delete Favorite Food",
                  "description": "Deletes a food with the given ID to the user's list of favorite foods.",
                  "operationId": "deleteFavoriteFood",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“delete”： { “标签”： [ “营养” ]， “摘要”： “删除最爱食物”， “description”： “删除用户最爱食物列表中指定 ID 的食物。”， “operationId”： “deleteFavoriteFood”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “food-id”， “in”： “path”， “description”： “用户收藏中要删除的食物 ID.”、“required”： true， “type”： “string” }， “responses”： { “204”： { “description”： “无内容。请求成功了。“ }， ”400“： { ”描述“：”糟糕的请求。请求很可能包含了错误的语法。“ }， ”401“： { ”description“： ”未授权。请求需要用户认证。“ }}， “安全”： [ { “OUth2”： [ “营养” ] } } }，

          "/1/user/-/meals.json": {
              "get": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Get Meals",
                  "description": "Returns a list of meals created by user in the user's food log in the format requested. User creates and manages meals on the Food Log tab on the website.",
                  "operationId": "getMeals",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              },
              "post": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Create Meal",
                  "description": "Creates a meal with the given food contained in the post body.",
                  "operationId": "addMeal",
                  "security": [
                      {
                          "oauth2": [
                              "nutrition"
                          ]
                      }
                  ]
              }
          },
“/1/user/-/meals.json”： { “get”： { “标签”： [ “营养” ]， “summary”： “Get Meals”， “description”： “返回用户在用户食物日志中创建的餐食列表，格式为所需。”用户在网站的食物日志标签页创建和管理餐食。“， ”operationId“： ”getMeals“， ”produces“： [ ”application/json“ ]， ”responses“： { ”200“： { ”description“： ”成功请求。“ }， ”400“： { ”description“： ”请求语法错误或本质上无法满足。“}， ”401“： { ”description“： ”请求需要用户认证。“}， ”403“： { ”description“： ”服务器理解请求，但拒绝履行。“ } }， “安全”： [ { “oauth2”： [ “营养” ] }， “post”： { “标签”： [ “营养” ]， “summary”： “创建餐食”， “description”： “创建餐食，包含帖子正文中的给定食物。”， “op[...]

          "/1/user/-/meals/{meal-id}.json":{
            "post": {
                "tags": [
                    "Nutrition"
                ],
                "summary": "Update Meal",
                "description": "Replaces an existing meal with the contents of the request. The response contains the updated meal.",
                "operationId": "updateMeal",
                "security": [
                    {
                        "oauth2": [
                            "nutrition"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Nutrition"
                ],
                "summary": "Delete Meal",
                "description": "Deletes a user's meal with the given meal id.",
                "operationId": "deleteMeal",
                "security": [
                    {
                        "oauth2": [
                            "nutrition"
                        ]
                    }
                ]
            }
          },
“/1/user/-/meals/{meal-id}.json”：{ “post”： { “标签”： [ “营养” ]， “summary”： “更新餐食”， “description”： “用请求内容替换现有餐食。响应包含更新后的餐食。“， ”operationId“： ”updateMeal“， ”consums“： [”application/json“]， ”produces“： [ ”application/json“ ]， ”parameters“： [ { ”in“： ”body“， ”name“： ”meal“， ”description“： ”准备制作的餐食“， ”required“： true， ”schema“： { ”$ref“： ”#/definitions/Meal“ } }， ”responses“： { ”200“： { ”description“： ”成功请求。“ }， ”400“： { ”description“： ”请求语法错误或本质上无法满足。“}， ”401“： { ”description“： ”请求需要用户认证。“ }， ”403“： { [...]

          "/1/user/-/foods/log/recent.json": {
              "get": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Get Recent Foods",
                  "description": "Returns a list of a user's frequent foods in the format requested. A frequent food in the list provides a quick way to log the food via the Log Food endpoint.",
                  "operationId": "getRecentFoods",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“/1/user/-/foods/log/recent.json”： { “get”： { “标签”： [ “营养” ]， “summary”： “获取近期食物”， “description”： “返回用户常用食物列表，格式为所需。列表中频繁出现的食物可以通过 Log Food 端点快速记录食物。“， ”operationId“： ”getRecentFoods“， ”produces“： [ ”application/json“ ]， ”responses“： { ”200“： { ”description“：”成功请求。“ }， ”400“： { ”description“：”请求语法错误或本质上无法满足。“}， ”401“： { ”description“： ”请求需要用户认证。“ }， ”403“： { ”description“： ”服务器理解了请求， 但却拒绝履行这个承诺。”}， “安全”： [ { “OUth2”： [ “营养” ] } } }，

          "/1/user/-/foods.json": {
              "post": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Create Food",
                  "description": "Creates a new private food for a user and returns a response in the format requested. The created food is found via the Search Foods call.",
                  "operationId": "addFoods",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“/1/user/-/foods.json”： { “帖子”： { “标签”： [ “营养” ]， “摘要”： “创建食物”， “描述”： “为用户创建一个新的私密食物，并返回要求格式的回复。创建的食物通过搜索食品调用“、”operationId“： ”addFoods“、”produces“： [ ”application/json“ ]， ”parameters“： [ { ”name“： ”name“， ”in“： ”query“， ”description“： ”食物名称.“、”required“： true， ”type“： ”string“ }， { ”name“： ”defaultFoodMeasurementUnitId“， ”in“： ”query“， ”description“： ”默认测量单元的 ID“，完整的单元列表可以通过获取食物单元端点“， ”required“： true， ”type“： ”string“ }， { ”name“： ”defaultServingSize“， ”in“： ”query“， ”description“： ”the size [...]

          "/1/user/-/foods/{food-id}.json": {
              "delete": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Delete Custom Food",
                  "description": "Deletes custom food for a user and returns a response in the format requested.",
                  "operationId": "deleteFoods",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“/1/user/-/foods/{food-id}.json”： { “delete”： { “tags”： [ “营养” ]， “summary”： “删除自定义食品”， “description”： “为用户删除自定义食物并返回请求格式的回复。”， “operationId”： “deleteFoods”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “food-id”， “in”： “path”， “description”： “要删除的食物 ID.”、“required”： true， “type”： “string” } ]， “responses”： { “204”： { “description”：“无内容。请求成功了。“ }， ”400“： { ”描述“：”糟糕的请求。请求很可能包含了错误的语法。“ }， ”401“： { ”description“： ”未授权。请求需要用户认证。“ }}， “安全”： [ { “OUth2”： [ “营养” ] } } }，

          "/1/foods/{food-id}.json": {
              "get": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Get Food",
                  "description": "Returns the details of a specific food in the Fitbit food databases or a private food that an authorized user has entered in the format requested.",
                  "operationId": "getFoodsInfo",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“/1/foods/{food-id}.json”： { “get”： { “tags”： [ “Nutrition” ]， “summary”： “获取食物”， “description”： “返回 Fitbit 食物数据库中特定食物的详细信息，或授权用户以请求格式输入的私人食物。”， “operationId”： “getFoodsInfo”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “food-id”， “in”： “path”， “description”： “食物 ID.”， “required”： true， “type”： “string” } ]， “responses”： { “200”： { “description”：“请求成功。” }， “400”： { “description”：“请求语法错误或本质上无法满足。”}， “401”： { “description”：“请求需要用户认证。”}， “403”： { “description”： “服务器理解请求，但拒绝履行。” } [...]

          "/1/foods/units.json": {
              "get": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Get Food Units",
                  "description": "Returns a list of all valid Fitbit food units in the format requested.",
                  "operationId": "getFoodsUnits",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
“/1/foods/units.json”： { “get”： { “标签”： [ “营养” ]， “summary”： “获取食品单元”， “description”： “返回所有有效 Fitbit 食品单元的列表，格式符合要求。”， “operationId”： “getFoodsUnits”， “produces”： [ “application/json” ]， “responses”： { “200”： { “description”：“成功请求。” }， “400”： { “description”： “请求语法错误或本质上无法满足。”}， “401”： { “description”： “请求需要用户认证。” }， “403”： { “描述”：“服务器理解了请求，但拒绝履行。” } }， “安全性”： [ { “oauth2”： [ “营养” ] } } }，

          "/1/foods/search.json": {
              "get": {
                  "tags": [
                      "Nutrition"
                  ],
                  "summary": "Search Foods",
                  "description": "Returns a list of public foods from the Fitbit food database and private food the user created in the format requested.",
                  "operationId": "getFoodsList",
                  "security": [
                      {
                          "oauth2": [
                            "nutrition"
                          ]
                      }
                  ]
              }
          },
          "/1.2/user/-/sleep/{log-id}.json": {
            "delete": {
                "tags": [
                    "Sleep"
                ],
                "summary": "Delete Sleep Log",
                "description": "Deletes a user's sleep log entry with the given ID.",
                "operationId": "deleteSleep",
“/1/foods/search.json”： { “get”： { “tags”： [ “营养” ]， “summary”： “搜索食品”， “description”： “返回 Fitbit 食物数据库中的公共食物列表，以及用户以请求格式创建的私人食物。”， “operationId”： “getFoodsList”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “query”， “in”： “query”， “description”： “URL 编码搜索查询.”， “required”： true， “type”： “string” } ]， “responses”： { “200”： { “description”：“成功请求。” }， “400”： { “描述”： “请求语法错误或本质上无法满足。” }， “401”： { “描述”： “请求需要用户认证。” }， “403”： { “描述”： “服务器理解请求，但拒绝履行。”} }， “安全性”： [ { “oauth2”： [ “营养” ] [...]

                ],
                "security": [
                    {
                        "oauth2": [
                           "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1.2/user/-/sleep/date/{date}.json": {
            "get": {
                "tags": [
                    "Sleep"
                ],
                "summary": "Get Sleep Log",
                "description": "The Get Sleep Logs by Date endpoint returns a summary and list of a user's sleep log entries (including naps) as well as detailed sleep entry data for a given day.",
                "operationId": "getSleepByDate",
                "parameters": [
                    {
                        "name": "date",
                        "in": "path",
                        "description": "The date of records to be returned. In the format yyyy-MM-dd.",
                        "required": true,
                        "type": "string",
                        "format": "date"
                    }
]， “回复”： { “204”： { “description”： “无内容。请求成功了。“ }， ”400“： { ”描述“：”糟糕的请求。请求很可能包含了错误的语法。“ }， ”401“： { ”description“： ”未授权。请求需要用户认证。“ }}， “安全性”： [ { “oauth2”： [ “活动”、“心率”、“位置”、“营养”、“个人资料”、“设置”、“睡眠”、“社交”、“体重”] } ] } }， “/1.2/user/-/sleep/date/{date}.json”： { “get”： { “标签”： [ “睡眠” ]， “summary”： “获取睡眠日志”， “description”： “按日期获取睡眠日志”端点返回用户的睡眠日志条目摘要和列表（包括午睡），以及当天的详细睡眠记录数据。” “operationId”： “getSleepByDate”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “date”， “in”： “path”， “description”： [...]

                ],
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1.2/user/-/sleep/date/{base-date}/{end-date}.json": {
            "get": {
                "tags": [
                    "Sleep"
                ],
                "summary": "Get Sleep Logs by Date Range",
                "description": "The Get Sleep Logs by Date Range endpoint returns a list of a user's sleep log entries (including naps) as well as detailed sleep entry data for a given date range (inclusive of start and end dates).",
                "operationId": "getSleepByDateRange",
                "parameters": [
                    {
                        "name": "base-date",
                        "in": "path",
                        "description": "The date of records to be returned. In the format yyyy-MM-dd.",
                        "required": true,
                        "type": "string",
                        "format": "date"
                    },
                    {
                        "name": "end-date",
                        "in": "path",
                        "description": "The date of records to be returned. In the format yyyy-MM-dd.",
                        "required": true,
                        "type": "string",
                        "format": "date"
                    }
]， “响应”： { “200”： { “描述”：“请求成功。” }， “401”： { “描述”： “请求需要用户认证。”}， “403”： { “描述”： “服务器理解请求，但拒绝履行。”} }， “安全性”： [ { “oauth2”： [ “活动”、“心率”、“位置”、“营养”， “个人资料”、“设置”、“睡眠”、“社交”、“体重” } } } }， “/1.2/user/-/sleep/date/{base-date}/{end-date}.json”： { “get”： { “标签”： [ “睡眠” ]， “摘要”： “按日期获取睡眠日志”范围“，”描述“：”按日期范围获取睡眠日志“端点返回用户的睡眠日志条目列表（包括午睡），以及给定日期范围的详细睡眠输入数据（包括开始和结束日期）。”， “operationId”： “getSleepByDateRange”， “produces”： [ “application/json” ]， “parameters”： [ { “name”： “base-date”， “in”： “path”， “description”： “要返[...]

                ],
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1.2/user/-/sleep/list.json": {
            "get": {
                "tags": [
                    "Sleep"
                ],
                "summary": "Get Sleep Logs List",
                "description": "The Get Sleep Logs List endpoint returns a list of a user's sleep logs (including naps) before or after a given day with offset, limit, and sort order.",
                "operationId": "getSleepList",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        }
 ]， “响应”： { “200”： { “描述”：“成功请求。” }， “401”： { “描述”： “请求需要用户认证。” }， “403”： { “描述”： “服务器理解请求，但拒绝履行。” } }， “安全性”： [ { “oauth2”： [ “活动”、“心率”、“位置”、“营养”， “个人资料”、“设置”、“睡眠”、“社交”， “体重” } }， “/1.2/user/-/sleep/list.json”： { “get”： { “标签”： [ “睡眠” ]， “摘要”： “获取睡眠日志列表”， “描述”：“获取”睡眠日志列表端点返回用户在某一天前后（包括午睡）的睡眠日志列表，包含偏移、限制和排序顺序。“， ”operationId“： ”getSleepList“， ”produces“： [ ”application/json“ ]， ”parameters“： [ { ”name“： ”beforeDate“， ”in“： ”query“， ”description“： ”格式为 yyyy-MM-ddTHH：mm：ss.只需要 yyyy-MM-dd。应指定日期之前或之[...]

        "/1.2/user/-/sleep/goal.json": {
            "get": {
                "tags": [
                    "Sleep"
                ],
                "summary": "Get Sleep Goal",
                "description": "Returns the user's sleep goal.",
                "operationId": "getSleepGoal",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            },
            "post": {
                "tags": [
                    "Sleep"
                ],
                "summary": "Update Sleep Goal",
                "description": "Create or update the user's sleep goal and get a response in the JSON format.",
                "operationId": "updateSleepGoal",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1.2/user/-/sleep.json": {
            "post": {
                "tags": [
                    "Sleep"
                ],
                "summary": "Log Sleep",
                "description": "Creates a log entry for a sleep event and returns a response in the format requested.",
                "operationId": "addSleep",
 “/1.2/user/-/sleep/goal.json”： { “get”： { “tags”： [ “Sleep” ]， “summary”： “获取睡眠目标”， “description”： “返回用户的睡眠目标。”， “operationId”： “getSleepGoal”， “produces”： [ “application/json” ]， “responses”： { “200”： { “description”：“成功请求。”}， “401”： { “description”： “请求需要用户认证。” }， “403”： { “description”： “服务器理解请求，但拒绝履行。”} }， “security”： [ { “oauth2”： [ “activity”， “heartrate”， “位置”、“营养”、“个人资料”、“设置”、“睡眠”、“社交”、“体重”]} ]， “post”： { “标签”： [ “睡眠” ]， “摘要”： “更新睡眠目标”， “description”： “创建或更新用户的睡眠目标并获得 JSON 格式的响应。”， “ope[...]

                ],
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/spo2/date/{date}.json": {
            "get": {
                "tags": [
                    "SpO2"
                ],
                "summary": "Get SpO2 Summary by Date",
                "description": "This endpoint returns the SpO2 summary data for a single date. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
                "operationId": "getSpO2SummaryByDate",
                "security": [
                    {
                        "oauth2": [
                           "oxygen_saturation"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/spo2/date/{startDate}/{endDate}.json": {
            "get": {
                "tags": [
                    "SpO2"
                ],
                "summary": "Get SpO2 Summary by Interval",
                "description": "This endpoint returns the SpO2 summary data for a date range. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
                "operationId": "getSpO2SummaryByInterval",
                "security": [
                    {
                        "oauth2": [
                           "oxygen_saturation"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/spo2/date/{date}/all.json": {
            "get": {
                "tags": [
                    "SpO2 Intraday"
                ],
                "summary": "Get SpO2 Intraday by Date",
                "description": "This endpoint returns the SpO2 intraday data for a single date. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
                "operationId": "getSpO2IntradayByDate",
                "security": [
                    {
                        "oauth2": [
                           "oxygen_saturation"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/spo2/date/{startDate}/{endDate}/all.json": {
            "get": {
                "tags": [
                    "SpO2 Intraday"
                ],
                "summary": "Get SpO2 Intraday by Interval",
                "description": "This endpoint returns the SpO2 intraday data for a specified date range. SpO2 applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
                "operationId": "getSpO2IntradayByInterval",
                "security": [
                    {
                        "oauth2": [
                           "oxygen_saturation"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/{collection-path}/apiSubscriptions.json": {
            "get": {
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Get a List of Subscriptions",
                "description": "Retreives a list of a user's subscriptions for your application in the format requested. You can either fetch subscriptions for a specific collection or the entire list of subscriptions for the user. For best practice, make sure that your application maintains this list on your side and use this endpoint only to periodically ensure data consistency.",
                "operationId": "getSubscriptionsList",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/{collection-path}/apiSubscriptions/{subscription-id}.json": {
            "post": {
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Add a Subscription",
                "description": "Adds a subscription in your application so that users can get notifications and return a response in the format requested. The subscription-id value provides a way to associate an update with a particular user stream in your application.",
                "operationId": "addSubscriptions",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            },
            "delete": {
                "tags": [
                    "Subscriptions"
                ],
                "summary": "Delete a Subscription",
                "description": "Deletes a subscription for a user..",
                "operationId": "deleteSubscriptions",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/temp/core/date/{date}.json": {
            "get": {
                "tags": [
                    "Temperature"
                ],
                "summary": "Get Temperature (Core) Summary by Date",
                "description": "Returns the Temperature (Core) data for a single date. Temperature (Core) data applies specifically to data logged manually by the user throughout the day.",
                "operationId": "getTempCoreSummaryByDate",
                "security": [
                    {
                        "oauth2": [
                            "temperature"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/temp/core/date/{startDate}/{endDate}.json": {
            "get": {
                "tags": [
                    "Temperature"
                ],
                "summary": "Get Temperature (Core) Summary by Interval",
                "description": "Returns Temperature (Core) data for a date range. Temperature (Core) data applies specifically to data logged manually by the user throughout the day and the maximum date range cannot exceed 30 days.",
                "operationId": "getTempCoreSummaryByInterval",
                "security": [
                    {
                        "oauth2": [
                            "temperature"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/temp/skin/date/{date}.json": {
            "get": {
                "tags": [
                    "Temperature"
                ],
                "summary": "Get Temperature (Skin) Summary by Date",
                "description": "Returns the Temperature (Skin) data for a single date. Temperature (Skin) data applies specifically to a user’s “main sleep”, which is the longest single period of time asleep on a given date.",
                "operationId": "getTempSkinSummaryDate",
                "security": [
                    {
                        "oauth2": [
                            "temperature"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/temp/skin/date/{startDate}/{endDate}.json": {
            "get": {
                "tags": [
                    "Temperature"
                ],
                "summary": "Get Temperature (Skin) Summary by Interval",
                "description": "Returns Temperature (Skin) data for a date range. It only returns a value for dates on which the Fitbit device was able to record Temperature (skin) data and the maximum date range cannot exceed 30 days.",
                "operationId": "getTempSkinSummaryByInterval",
                "security": [
                    {
                        "oauth2": [
                            "temperature"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/badges.json": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get Badges",
                "description": "Retrieves the user's badges in the format requested. Response includes all badges for the user as seen on the Fitbit website badge locker (both activity and weight related.) The endpoint returns weight and distance badges based on the user's unit profile preference as on the website.",
                "operationId": "getBadges",
                "security": [
                    {
                        "oauth2": [
                            "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "weight"
                        ]
                    }
                ]
            }
        },
        "/1/user/-/profile.json": {
            "get": {
                "tags": [
                    "User"
                ],
                "summary": "Get Profile",
                "description": "Returns a user's profile. The authenticated owner receives all values. However, the authenticated user's access to other users' data is subject to those users' privacy settings. Numerical values are returned in the unit system specified in the Accept-Language header.",
                "operationId": "getProfile",
                "security": [
                    {
                        "oauth2": [
                            "location",
                            "profile",
                            "weight"
                        ]
                    }
                ]
            }
        },
            "post": {
                "tags": [
                    "User"
                ],
                "summary": "Update Profile",
                "description": "Updates a user's profile using a form.",
                "operationId": "updateProfile",
                "security": [
                    {
                        "oauth2": [
                           "activity",
                            "heartrate",
                            "location",
                            "nutrition",
                            "profile",
                            "settings",
                            "sleep",
                            "social",
                            "temperature",
                            "weight"
                        ]
                    }
                ]
            }
 ]， “响应”： { “200”： { “描述”：“请求成功。” }， “401”： { “描述”： “请求需要用户认证。” }， “403”： { “描述”： “服务器理解请求，但拒绝履行。” } }， “安全性”： [ { “oauth2”： [ “活动”、“心率”、“位置”、“营养”、“个人资料”、“设置”、“睡眠”、“社交”、“体重” }， “/1/user/-/spo2/date/{date}.json”： { “get”： { “标签”： [ “SpO2” ]， “摘要”： “按日期获取 SpO2 摘要”， “描述”：“此端点返回单一日期的 SpO2 摘要数据。SpO2 专门适用于用户的“主要睡眠”，即在特定日期内睡眠时间最长的单一时间。“， ”operationId“： ”getSpO2SummaryByDate“， ”produces“： [ ”application/json“ ]， ”parameters“： [ { ”name“： ”date“， ”in“： ”path“， ”description“： ”yyyy-MM-dd 格式的日期或今天。“， ”requ[...]

    },
    "securityDefinitions": {
        "oauth2": {
            "type": "oauth2",
            "authorizationUrl": "https://www.fitbit.com/oauth2/authorize",
            "flow": "implicit",
            "scopes": {
                "activity": "Activity data and exercise log related features, such as steps, distance, calories burned, and active minutes",
                "cardio_fitness": "Maximum or optimum rate at which the user’s heart, lungs, and muscles can effectively use oxygen during exercise",
                "electrocardiogram": "A users on-device ECG readings",
                "heartrate": "Continuous heart rate & HRV data and related analysis",
                "irregular_rhythm_notifications": "Includes the users engagement and list of irregular rhythm notification alerts.",
                "location": "GPS and other location data",
                "nutrition": "Calorie consumption and nutrition related features, such as food/water logging, goals, and plans",
                "oxygen_saturation": "SpO2 (Oxygen Saturation) is a measurement of your blood oxygen level",
                "profile": "Basic user information",
                "respiratory_rate": "Respiratory Rate is a measurement of your breaths at night.",
                "settings": "User account and device settings, such as alarms",
                "sleep": "Sleep logs and related sleep analysis",
                "social": "Friend-related features, such as friend list and leaderboard",
                "temperature": "Core and skin temperature data",
                "weight": "Weight and related information, such as body mass index, body fat percentage, and goals"
            }
        }
    }
}， “securityDefinitions”： { “oauth2”： { “type”： “oauth2”， “authorizationUrl”： “https://www.fitbit.com/oauth2/authorize”， “flow”： “implicit”， “scopes”： { “活动”： “活动数据及运动日志相关特征，如步数、距离、燃烧卡路里和活动分钟数”，“cardio_fitness”：“用户在运动时心脏、肺和肌肉有效利用氧气的最大或最佳速率”，“心电图”：“用户设备内心电图读数”，“心率”：“连续心跳”心率和心率变异数数据及相关分析“，”irregular_rhythm_notifications“：”包含用户参与度及不规则节律通知警报列表。“位置”：“GPS 及其他位置数据”，“营养”：“热量摄入及营养相关特征，如食物/水分记录、目标和计划”，“oxygen_saturation”：“血氧饱和度（SpO2）是你的血氧水平的测量指标”，“画像”：“基本用户信息”， “respiratory_rate”：“呼吸频率是你夜间呼吸的测量。”，“设置”：“用户[...]

            }
        },
        "FoodItem": {
            "type": "object",
            "properties": {
                "foodId": {
                    "type": "integer"
                },
                "amount": {
                    "type": "integer"
                },
                "unitId": {
                    "type": "integer"
                }
            }
        }
    }
}

} }， “FoodItem”： { “type”： “object”， “properties”： { “foodId”： { “type”： “整数”， “example”： 82782 }， “amount”： { “type”： “整数”， “example”： 8 }， “unitId”： { “type”： “整数”， “example”： 128 } } } }， “externalDocs”： { “description”： “完整文档”， “url”： “https://dev.fitbit.com/build/reference/web-api/” } }

